/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface AppApps {}
  interface AppAppsAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppLogin {}
  interface AppLoginAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppApps': Components.AppApps;
    'AppHome': Components.AppHome;
    'AppLogin': Components.AppLogin;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-apps': Components.AppAppsAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-login': Components.AppLoginAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppAppsElement extends Components.AppApps, HTMLStencilElement {}
  var HTMLAppAppsElement: {
    prototype: HTMLAppAppsElement;
    new (): HTMLAppAppsElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {}
  var HTMLAppLoginElement: {
    prototype: HTMLAppLoginElement;
    new (): HTMLAppLoginElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-apps': HTMLAppAppsElement
    'app-home': HTMLAppHomeElement
    'app-login': HTMLAppLoginElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-apps': HTMLAppAppsElement;
    'app-home': HTMLAppHomeElement;
    'app-login': HTMLAppLoginElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
